#!/usr/bin/env bash

set -xe

rm -f eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe.tif
gdal_translate -of GTiff -outsize 1000 0  "WMS:https://view.eumetsat.int/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=mtg_fd%3Argb_geocolour&CRS=CRS:84&BBOX=11.080,46.900,23.549,51.850&FORMAT=image/jpeg&TILESIZE=256&OVERVIEWCOUNT=17&MINRESOLUTION=0.0000053644180298&TILED=true" eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe.tif

rm -f eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries.tif
cp eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe.tif eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries.tif
gdal_rasterize -b 1 -b 2 -b 3 -burn 255 -burn 255 -burn 255 -l ne_10m_admin_0_boundary_lines_land_central_europe naturalearthdata_boundary_lines_central_europe/ne_10m_admin_0_boundary_lines_land_central_europe.shp eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries.tif

rm -f eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries_mercator.tif
gdalwarp -t_srs ESRI:53004 -r lanczos -wo SOURCE_EXTRA=1000 -co COMPRESS=LZW eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries.tif eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries_mercator.tif

rm -f eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries_mercator.jpg
gdal_translate -of JPEG -scale eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries_mercator.tif eumetsat_mtg_geocolour_rgb_central_europe/eumetsat_rgb_central_europe_plus_boundaries_mercator.jpg
