---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: server
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
      - name: artifacts
        emptyDir: {}
      containers:
      - name: generator
        image: ghcr.io/phoracek/clouds-over-czechoslovakia:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do /opt/clouds/entrypoint.sh $TARGET; sleep 600; done"]
        env:
        - name: TARGET
          value: /opt/artifacts
        volumeMounts:
        - name: artifacts
          mountPath: /opt/artifacts
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: artifacts
          mountPath: /usr/share/nginx/html
